import localFont from "next/font/local";
import "./globals.css";
import { Karla } from "next/font/google"; // Import the Google Font

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const karla = Karla({
  subsets: ["latin"], // You can add more subsets as needed
  weights: ["400", "700"], // Specify the weights you want to use
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${karla.className} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
